language: julia

os:
  - linux

julia: 
  - 1.5

env:
  DATADEPS_ALWAYS_ACCEPT=1 JIVE_PROCS=2  

jobs:
  include:   
  
    - stage: "Unit Tests"    
      script:
        - julia --project -e 'using Pkg; Pkg.develop(PackageSpec(name="LogicCircuits")); Pkg.instantiate(); Pkg.build();'
        - julia --project --check-bounds=yes --depwarn=error -e 'import Pkg; Pkg.test(; coverage=true)'
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'

    - stage: "Documentation"
      script:
        - sudo apt-get -qq update
        - sudo apt-get install pdf2svg
        - sudo apt-get install -y texlive-latex-recommended texlive-pictures  texlive-latex-extra texlive-luatex texlive-xetex latexmk
        - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended
        - sudo apt-get install poppler-utils
        - sudo apt-get install -y texlive-binaries
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(name="LogicCircuits")); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    rooms:
      - secure: VMXOgM9g758gZiU06/Gaahns6CFpoSuDYMnl9g0LMv165HEe7tZPlF1IFbTEXk6svr+tAuSEd3oxs/kAyK7onI3hIpP0PSc+Y7/+rnOMk8zU+z7R6JEzQKHHb1M6pQ6MjzOia9BM7SfcfVqedPREVXZx+XJPmVuR4BgTOxUnnyfltZzW0ldSbyeJ37FdDSd9SDRRf7Q4UzbEMN33GfVsTKMZoRqASrZXhvqAVp7deXMdGp1kNlvIbbwVkeICLYTIYrm5zd0HkH2yEhk0AtgeTpyx/kkR1T0Fs2+PCDsLRPhP1EEJs7FdsdQJuP0SueJ92GpPd7yLYZVVWWQkGWudNb6H3iYp2xtbZCoeCBLEUgusrawwdxp0OlNOgP/aeJDc+zNy59ikraluI0sNCV1Pl8dIXu8Ihu6e7W6hoiTQ8K9PjwcXSmBgUsR+kXD8NcCx73RTxynokv+24Xk0M1pkJhu6mjNjZBDIegXVM/CnNew1LSMoMjdi43asuDiDbkZg2uCxfHwaMxlgWuM/M38r662FbOjEfgr13fhCyuUQZRFOKvvqU17HbA+ewC/J40C2g0sBDGPu/uOJsDJaQGPXDpXsh4G+8R7uZRNunhwNPK4OnVdY+uVnYlD+9TG9T1IothaDSRJvYU8HwAcUOJhMNYDDQosWOy+01NQtX0IYRgk=
