[density_estimation_datasets]
git-tree-sha1 = "1bc8564650a08d7b7a646bcaae171db096aed7a3"
lazy = true

 [[density_estimation_datasets.download]]
    url = "https://github.com/UCLA-StarAI/Density-Estimation-Datasets/archive/v1.0.1.tar.gz"
    sha256 = "5d66a95037e44010502ad28ec8d6dc26f46947dc88e962633b7de54e614b1a47"

[circuit_model_zoo]
git-tree-sha1 = "49e3a134c68acbcd87075dee811aff997c29cad2"
lazy = true

 [[circuit_model_zoo.download]]
    url = "https://github.com/UCLA-StarAI/Circuit-Model-Zoo/archive/v0.1.3.tar.gz"
    sha256 = "537d4d414b8955e8f9b64e4e3aaf5382889a6901c5e24aa9bc8bc2fbea51dc4f"