name: Slow Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  # tests are not being maintained so don't run on pull requests
  # pull_request:
  #   branches:
  #     master

  schedule:
    - cron: '0 0 */7 * *'

  workflow_dispatch:


env:
  DATADEPS_ALWAYS_ACCEPT: 1
  JIVE_PROCS: 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6

      # Runs a single command using the runners shell
      - name: Unit Tests
        run: |
          julia --project=test -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.precompile();'
          julia --project=test -e 'using Pkg; Pkg.develop("ProbabilisticCircuits");'
          julia --project=test --check-bounds=yes --depwarn=yes test/_manual_/strudel_marginal_tests.jl
          julia --project=test --check-bounds=yes --depwarn=yes test/_manual_/strudel_likelihood_tests.jl
          julia --project=test --check-bounds=yes --depwarn=yes test/_manual_/ensembles_tests.jl


